services:

  frontend:
    image: nginx
    volumes:
      - ./html/:/usr/share/nginx/html/
    ports:
      - 80:80
    container_name: frontend
    networks:
      - compute_network

  hub:
    build:
      context: ./hub
    ports:
      - 8080:8080
      - 13021:13021
    container_name: hub
    networks:
      - compute_network

  # spoke:
  #   build:
  #     context: ./spoke
  #   environment:
  #     - HUB_URL=hub:13021
  #     - THREADS=4
  #   container_name: spoke1
  #   networks:
  #     - compute_network
  
  # spoke-2:
  #   build:
  #     context: ./spoke
  #   environment:
  #     - HUB_URL=hub:13021
  #     - THREADS=4
  #   container_name: spoke2
  #   networks:
  #     - compute_network

  # spoke-3:
  #   build:
  #     context: ./spoke
  #   environment:
  #     - HUB_URL=hub:13021
  #     - THREADS=4
  #   container_name: spoke3
  #   networks:
  #     - compute_network

  # spoke-4:
  #   build:
  #     context: ./spoke
  #   environment:
  #     - HUB_URL=hub:13021
  #     - THREADS=4
  #   container_name: spoke4
  #   networks:
  #     - compute_network


networks:
  compute_network: