services:

  spoke:
    build:
      context: ./spoke
    environment:
      - HUB_URL=cluster.servers:31668
      - THREADS=16
    container_name: spoke
    networks:
      - compute_network


networks:
  compute_network: