[package]
name = "distributed_pi_project_spoke"
version = "0.2.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
rug = "1.27.0"
derive_more = { version = "1", features = ["full"] }
serde = { version = "1.0.209", features = ["derive"] }
