FROM rust:alpine AS builder

WORKDIR /usr/build/

RUN apk add gmp-dev mpc1-dev mpfr-dev musl-dev diffutils m4 make gcc

COPY . .

RUN cargo build --release

FROM alpine


WORKDIR /usr/bin/

RUN apk add gmp-dev mpc1-dev mpfr-dev

COPY --from=builder /usr/build/target/release/distributed_pi_project_spoke ./spoke 


EXPOSE 8080
EXPOSE 13021

CMD ["./spoke"]